version: '3'
services:
  php:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: